//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusHelperDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusInfo_Vehicle
    {
        public int id { get; set; }
        public Nullable<int> bus_info_id { get; set; }
        public Nullable<int> vehicle_id { get; set; }
    
        public virtual BusInfo BusInfo { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
