//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusHelperDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> bus_stop_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual BusStop BusStop { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
