//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusHelperDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusHelperEntities : DbContext
    {
        public BusHelperEntities()
            : base("name=BusHelperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beacon> Beacons { get; set; }
        public virtual DbSet<Beacon_BusStop> Beacon_BusStop { get; set; }
        public virtual DbSet<BusInfo> BusInfoes { get; set; }
        public virtual DbSet<BusInfo_BusStop> BusInfo_BusStop { get; set; }
        public virtual DbSet<BusInfo_Vehicle> BusInfo_Vehicle { get; set; }
        public virtual DbSet<BusStop> BusStops { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<UserToken> UserTokens { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
    }
}
